id = "pdf-math-translate"
name = "PDF Math Translate"
version = "1.0.0"
description = "A tool for translating mathematical formulas in PDF documents"
icon = "assets/icons/pdf-math.png"
cover_image = "public/640.png"
package_type = "git"
introduction = "Advanced PDF mathematical formula translation tool with OCR capabilities"
service_notes = "Requires internet connection for initial model download"
platforms = ["windows", "macos", "ubuntu"]
category = "document"
created_at = "2024-01-01"
updated_at = "2024-03-15"

[device_support]
cpu = true
nvidia = true

[requirements]
ram = "8GB"
vram = "4GB"
disk_space = "2GB"

[download]
git_url = "https://github.com/Byaidu/PDFMathTranslate"
branch = "main"
python_version = "3.12"


[windows]
startup = "pdf2zh -i -o ${output}/pdf2zh_files "
shutdown = ""

[macos]
startup = "pdf2zh -i -o ${output}/pdf2zh_files "
shutdown = ""

[linux]
startup = "pdf2zh -i -o ${output}/pdf2zh_files "
shutdown = ""
